### ISSUE TITLE
Navigation Stack Not Needed?

### ISSUE THREAD

**Issue by david-barrette** [werewolves-online/werewolves#10]
https://github.com/werewolves-online/werewolves/blob/4844ef778dbdbc66152c47d8821b1a822ae1efd6/werewolves/lib/utils/navigator/navigator_stack.dart#L24-L25

**Comment by ammaratef45** [comment]
one way to avoid having this problem is to use route-based navigation
A tutorial can be found here: https://docs.flutter.dev/cookbook/navigation/named-routes
A usage example is shown in the PR #13 

look for the keywords `routes` `popAndPushNamed` and `pushNamed`

**Comment by david-barrette** [comment]
I removed it

**Comment by ammaratef45** [comment]
@david-barrette usually I'd close the issue after the PR that resolves it is merged
It's a good practice to reference what PR resolves it as well
